<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyName>DetectorGui</AssemblyName>
    <RootNamespace>Detector.Gui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Detector.Core\Detector.Core.csproj" />
  </ItemGroup>

</Project>
